# Site settings
title: Final Touch Painting
email: your-email@domain.com
description: "Final Touch Painting offers a wide range of coating solutions for residential, commercial and industrial needs."
baseurl: ""
url: "http://ftpdenver.com"
twitter_username: ftpdenver
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty
