# Site settings
title: Final Touch Painting
email: your-email@domain.com
description: "Final Touch Painting offers a wide range of coating solutions for residential, commercial and industrial needs."
baseurl: ""
url: "http://ftpdenver.com"
twitter_username: ftpdenver
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty

google_analytics: true
google_analytics_id: UA-50387096-6

sitemap:
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
